# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema.users]
file = "src/modules/user/schema.rs"
with_docs = true
filter = { only_tables = ["users"] }

[migrations_directory]
dir = "/Users/jcho114/Documents/GitHub/fucking-around/actix-testing/migrations"
